### ISSUE TITLE
Unexpected token: name (rightSize) [./~/random-words/index.js:260,0]

### ISSUE THREAD

**Issue by freedomhunter** [punkave/random-words#16]
I am getting this error when i run 'npm run build' and it fails my build in production mode but everything is working fine in development mode ' npm start '. Can anyone tell me what's the issue?

**Comment by boutell** [comment]
You're trying to use the module in an environment that doesn't support ES6, specifically "let" statements. Either you're passing it through an old version of uglifyjs, or you're trying to use it in IE11, or you're running it on a truly archaic version of Node, i.e. Node 4 or earlier. (If you are: yikes, stop doing that today, it hasn't received security updates in years.)

But, you're in luck: the whole module looks to still be ES5 compatible except for two lines of code that used "let". So I changed those back to "var" to be consistent with the rest of the module and published version 1.1.1.

This module will no doubt migrate to ES6 at some point, but there is no urgency on that.
